#!/usr/bin/env python3

"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

from utils import *
import itertools

def solve(max_number):
    less_than_max = itertools.takewhile(lambda x: x < max_number, fibonaccis())
    evens = filter(lambda x: x%2==0, less_than_max)
    return sum(evens)

def test():
    assert(solve(4000000) == 4613732)

def result():
    return 4613732

if __name__ == "__main__":
    print(result())

